In [1]:
import numpy as np
oned = np.array([1,2,3,4]) #vector
twod = np.array([[1,2,3],[4,5,6]])#matrix
threed =  np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #tensor


WAYS TO CREATE ARRAYS IN NUMPIES


In [37]:
import numpy as np

np.array([1,2,3],dtype=float)
np.array([1,2,3,4],dtype=bool)
np.array([1,2,3],dtype=np.int32)
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [38]:
#arange is  same as range
# numpy.arange([start,] stop[, step,][, dtype=None])
# nction, the dtype argument is used to specify the data type of the resulting array. However, dtype expects a data type (like int, float, etc.), not a Boolean value.

np.arange(1,10,2,dtype=float) # last one not included

array([1., 3., 5., 7., 9.])

In [39]:

np.arange(1,11).reshape(2,5) # row x col
a =  np.arange(5)
new_a =  np.reshape(a,(5,1)) 
# no product should be equal to total array elements


In [40]:
np.ones((2,2),dtype=int) # default type float
np.zeros ((2,2),dtype=bool)
# use : ghn bh foran koi value initiazlize krni h with digit u may use np.ones or np.zeros or random values
np.zeros((1,10),dtype=int)
np.random.random((2,2))
# The np.random.random function in NumPy does not have a dtype parameter. It generates random floating-point numbers between 0 and 1 in the specified shape. If you want integers, you should use np.random.randint instead
np.random.randint(0,10,(5,2))

array([[3, 0],
       [3, 2],
       [7, 9],
       [7, 6],
       [9, 1]], dtype=int32)

In [41]:
# np.linspace creates numbers evenly spaced between two values.
np.linspace(-10,11,10)
# by default last range value i.e here 11 is include but to exlude it you may use a paramter endpoint=false in it
np.linspace(-10,11,10,endpoint=False)
#creates identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NUMPY ATTRIBUTES

In [ ]:
#ndim tells the dimensions of the given array
a = np.arange(1,10)
a.ndim


1

In [1]:
#shape : tells elements in each dimension
a.shape

NameError: name 'a' is not defined

In [ ]:
# itemsize : tells size of every element 
# itemsize attribute tells you the size in bytes of each element in a NumPy array


# Create an array of integers (default is 64-bit integer)
arr = np.array([1, 2, 3])
print((arr.itemsize)) 
# Output: 8 (each integer takes 8 bytes)

# Create an array of 32-bit floats
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(arr_float.itemsize)  
# Output: 4 (each float takes 4 bytes)



24
4


In [49]:
#dtype : tells the datatype of your elements/ numpy array
print(arr.dtype)

int64


In [54]:
# In NumPy, astype is a method used to convert the data type of an array to a different type. It creates a new array with the specified data type, leaving the original array unchanged.

# array.astype(new_type)
import numpy as np
demo = np.arange(1,11).reshape(5,2)
test = demo.astype(bool)
print(test)


[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [2]:
#  change the data type to int8  of given  2d array i.e middle row
array = np.arange(1,10).reshape(3,3)
print('BEFORE CHANAGE')
for i in range(len(array)):
    for j in range(len(array[0])):
        print(np.dtype(array[i][j]),end= " ")
    print(' ')
print(" ")
print("AFTER CHANGE: ")

for i in range(len(array)):
    array[i][1] = np.int8(array[i][1])
for i in range(len(array)):
    for j in range(len(array[0])):
        print(np.dtype(array[i][j]),end= " ")
    print(' ')

BEFORE CHANAGE
int64 int64 int64  
int64 int64 int64  
int64 int64 int64  
 
AFTER CHANGE: 
int64 int64 int64  
int64 int64 int64  
int64 int64 int64  
