In [11]:
import numpy as np
a1 = np.arange(1,10).reshape(3,3)
a2  =  np.arange(8).reshape(2,2,2)
print(a2)
a2[1,0:1]
# arr[row, column]
# arr[row, start:end]  # Slice along columns (range of columns)
# arr[start:end, :]    # Slice along rows (range of rows)



[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[4, 5]])

ITERATION

In [16]:
for i in np.nditer(a1):  # iteratiing
  print(i , end= " ")
print(" ")
for j in np.nditer(a2):  # iteratiing
#   print(j , end= " ")
# np.nditer() is used to iterate over each element of an array, no matter its shape (1D, 2D, etc.).
# It flattens the array, meaning it will visit each element in a single sequence (left to right, top to bottom for multidimensional arrays)

1 2 3 4 5 6 7 8 9  
0 1 2 3 4 5 6 7 

TRANSPOSE

In [19]:
#Transpose
np.transpose(a2)
# or
a2.T


array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

RAVEL

In [22]:
#Ravel
#converts n - dimension array into 1d array
a2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

STACKING

In [27]:
#In NumPy, stacking refers to combining multiple arrays along a new axis (row-wise, column-wise, or depth-wise) to create a larger array.
# There are several methods to stack arrays in NumPy:


# Example arrays
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

# Correct horizontal stacking
x = np.hstack((a1, a2)) #hstack = horizontal stack
y = np.vstack((a1,a2)) # vertical stack
#if x :   [2 x 2]  :  [2 x 2 ]  =  [2 x 4]
#if y :   [2 x 2]  :  [2 x 2 ]  =  [4 x 2]



[[1 2 3]
 [4 5 6]]


In NumPy, concatenation refers to combining two or more arrays along a specified axis (0 for rows, 1 for columns, etc.). This can be done using the function np.concatenate(), which is more general and flexible compared to other stacking functions like np.vstack() and np.hstack().

In [30]:
#np.concatenate((array1, array2, ...), axis=0)
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
g = np.concatenate((a1,a2),axis=0)


SPILITING


Horizontal Split (np.hsplit())
The function np.hsplit() splits a 2D array horizontally (i.e., it cuts along columns), meaning the array is divided into multiple smaller arrays along its columns.

Vertical Split (np.vsplit())
The function np.vsplit() splits a 2D array vertically (i.e., it cuts along rows), meaning the array is divided into multiple smaller arrays along its rows.

In [36]:
#in horizontal ; numpy arrays s cut vertically so two arrays are form horizontaly
#in vertically ; numpy arrays s cut horizontally so two arrays are form vertically

# Define a 2D array (2x3 matrix)
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Split the array into 2 parts horizontally (along columns)
result1 = np.hsplit(arr1, 1)

# Split the array into 2 parts vertically (along rows)
result2 = np.vsplit(arr1, 1)

# Print the result of the split
print(result1)
print(result2)



[array([[1, 2, 3],
       [4, 5, 6]])]
[array([[1, 2, 3],
       [4, 5, 6]])]
