In [ ]:
import numpy as np

CORRCOEF:CO-RELAION COFFICIENT

The correlation coefficient, often denoted as r.
It measures the strength and direction of a linear relationship between two variables. It provides a value between -1 and +1:

+1: Perfect positive correlation — as one variable increases, the other also increases in a perfectly linear manner.

-1: Perfect negative correlation — as one variable increases, the other decreases in a perfectly linear manner.
0: No correlation — there is no linear relationship between the two variables.


In [ ]:
#koi do quantities  kitni co realated hen apas ma , ik k change s dosre pr frq
salary  =  np.array([100,200,300,400,500])
exp = np.array([1,2,3,1,10])
np.corrcoef(salary,exp)

array([[1.        , 0.71080571],
       [0.71080571, 1.        ]])

ISIN

checks if items are present in given array or not , take both single and multiple items to search and return boolean ans


In [ ]:
items =  np.array([10,20,30,40,50,60,70,80,100])
main_array = np.array([10,30,60,100])
np.isin(main_array,items)

array([ True,  True,  True,  True])

FLIP

Reverse the elements while shape remains same


In [ ]:
a =  np.array([10,20,30,40,50,60,70,809,90]).reshape(3,3)
print(a)
# for 2 d arrays both col and row  wise reverse  by default
np.flip(a)
np.flip(a,axis=0)
np.flip(a,axis=1)


[[ 10  20  30]
 [ 40  50  60]
 [ 70 809  90]]


array([[ 30,  20,  10],
       [ 60,  50,  40],
       [ 90, 809,  70]])

PUT

Replaces array with speciefied index in the orignal array

In [ ]:
a =  np.array([10,20,30,40,50,60,70,809,90])
b =  np.array([10,20,30,40,50,60,70,809,90]).reshape(3,3)
print(b)
np.put(a,[0,1],[200,900])
#np put works clearry with flat/1d arrays to change a value for 2 d use indexing
b[0,1] = 900

print(b)

[[ 10  20  30]
 [ 40  50  60]
 [ 70 809  90]]
[[ 10 900  30]
 [ 40  50  60]
 [ 70 809  90]]


DELETE


In [ ]:
a =  np.array([10,20,30,40,50,60,70,809,90]).reshape(3,3)
b =  np.array([10,20,30,40,50,60,70,809,90])
np.delete(b,[0,1,2])
print(a)
np.delete(a,1,axis=1)
np.delete(a,2,axis=0)



[[ 10  20  30]
 [ 40  50  60]
 [ 70 809  90]]


array([[10, 30],
       [40, 60],
       [70, 90]])

SET FUNCTIONS

UNION

In [ ]:
b =  np.array([10,20,30,40])
a =  np.array([50,60,70,809,90])
np.union1d(a,b)


array([ 10,  20,  30,  40,  50,  60,  70,  90, 809])

INTERSECTION

In [ ]:
a =  np.array([10,20,30,40])
b =  np.array([50,60,10,40])
np.intersect1d(a,b)

array([10, 40])

DIFFERENCE

Wo items jo srf phle set m hen dosre m nh

In [ ]:
a =  np.array([10,20,30,40])
b =  np.array([50,60,10,40])
np.setdiff1d(a,b)
np.setdiff1d(b,a)

array([50, 60])

SET XOR

remove common from both arrays

In [ ]:
a =  np.array([10,20,30,40])
b =  np.array([50,60,10,40])
np.setxor1d(a,b)

array([20, 30, 50, 60])

CLIP

removes elements that are not with in specified range


In [46]:

a = np.arange(1, 100)  # This creates an array of integers from 1 to 99
result = np.clip(a, a_min=30, a_max=60)  # Clips values less than 30 to 30, and values greater than 60 to 60
print(result)
# This is the expected result when clipping the array.
# The values below 30 are replaced with 30, and the values above 60 are replaced with 60,
# while the values between 30 and 60 remain as they are.


[30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60]
