In [10]:
import numpy as np
#expand dimensions
# The numpy.expand_dims function is used to add a new axis (or dimension) to a NumPy array, which effectively increases the dimensionality of the array.
# numpy.expand_dims(a, axis)

# It can also be useful when preparing data for machine learning models, where input arrays need specific dimensionalities (e.g., adding a batch dimension to data).
# in the context of machine learning, a batch refers to a subset of the dataset that is processed together in a single iteration of training or inference.

# The concept of a batch is closely tied to batch processing, which helps efficiently manage large datasets by splitting them into smaller chunks (batches) for easier handling and faster computat
array = np.arange(10)
print(np.expand_dims(array,axis=0).shape) #converts 1d array into 2d #1 row - 10 col
print(np.expand_dims(array,axis=1)) # converts 1d-array into 2d #1 col - 10 rows



(1, 10)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


WHERE

Returns all the indices to which given condition is fullfilled

In [14]:
# numpy.where(condition, [x, y])
# condition: An array-like object (e.g., a NumPy array or a condition) that returns True or False for each element.
# x: Values to select when the condition is True.
# y: Values to select when the condition is False.
# The x and y parameters are optional. If only the condition parameter is provided, numpy.where will return the indices of the elements where the condition is True.
a =  np.arange(10)
# np.where(a>4)    #returns only the indices where value is greater than 4
np.where(a>4 , "it is greater than 4","it is less than 4")
np.where((a>5) & (a<10) , "It is between 5 and 10 ","Out of range") # WHEN FOR AND CONDTION  USE &
# No, arrays are not scalars. In NumPy, scalars refer to single values (e.g., a single number), while arrays are collections of values.
# hen you're working with arrays and need to combine multiple conditions, you must use the bitwise operators like & (AND), | (OR), and ~ (NOT),
#  rather than the logical operators like and, or, and not which are meant for scalar (single value) operations.
# and, or, and not are logical operators used to combine boolean values in Python. These operators work with single boolean values (i.e., scalars), not with arrays.


array(['Out of range', 'Out of range', 'Out of range', 'Out of range',
       'Out of range', 'Out of range', 'It is between 5 and 10 ',
       'It is between 5 and 10 ', 'It is between 5 and 10 ',
       'It is between 5 and 10 '], dtype='<U23')

ARGMAX and ARGMIN


In [ ]:
# NumPy, argmax is a function that returns the index of the maximum value along a specified axis or in the entire array.
# It is commonly used to find the position of the largest element in an array


In [36]:
a =  np.arange(1,10).reshape(3,3)
b =  np.random.randint(1,100,size=9).reshape(3,3)
print(np.argmin(a))
print(b)
np.argmax(a) # returnds 8 , which is the index of 9
np.argmax(b,axis=1) #0 along y axis
np.argmax(b,axis=0) #1 along x axis

0
[[93 83 12]
 [64 14  8]
 [32 48 94]]


array([0, 0, 2])

CUMSUM

np.cumsum() returns the cumulative sum of an array. The cumulative sum means that each element in the output array is the sum of all previous elements up to that position, including the current one.

In [40]:
# computes the total sum of an array (i.e., the sum of all elements in the array).
#  It does not return an array; instead, it returns a single scalar value that is the sum of all elements.
array  =  np.random.randint(1,100,size=9).reshape(3,3)
print(array)
np.cumsum(array,axis=0)


[[63 59 96]
 [66 43  1]
 [34 37 42]]


array([[ 63,  59,  96],
       [129, 102,  97],
       [163, 139, 139]])

CUMPRODUCT

np.cumprod() works in a similar way to np.cumsum(), but instead of summing elements cumulatively, it calculates the cumulative product. This means it computes the product of elements up to the current position, rather than the sum.

PERCENTILE

A percentile indicates the relative position or rank of a score within a given dataset. It tells you the percentage of data points that fall below a particular value. For example, if you're in the 90th percentile, it means you scored higher than 90% of the people or data points in that group.



In [44]:
b =  np.random.randint(1,100,size=9)
print(b)
np.percentile(b,100)
np.percentile(b,0)

[86 76 46 54 62 50 62 12 79]


12.0

HISTOGRAM

In [47]:
b =  np.random.randint(1,100,size=10)
print(b)
# The function np.histogram() in NumPy is used to compute the histogram of a set of data
# . It essentially divides the data into specified bins (intervals) and counts how many data points fall into each bin.
np.histogram(b,bins=[10,20,30,40,50,60,70,80,90,100])
#  : values between 0-10 , 10-20 , 20-30 they are bins

[69 28 10 39 69 44 49 80 67 72]


(array([1, 1, 1, 2, 0, 3, 1, 1, 0]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))