NUMPY TRICKS


SORTING


In [31]:
import numpy as np
#sort
a = np.arange(1,10).reshape(3,3)
np.sort(a) #np.sort .
#the reason we are not using pything sort is that that will return python list not numpy array
b = np.random.randint(1,100,9).reshape(3,3)
print(np.sort(b,axis=1)) #by default row wise : axis 1
print(np.sort(b,axis=0))# col wise :axis 1
#sort decending
print(np.sort(a)[::-1])  #sort decending vice



[[50 53 86]
 [ 7  9 71]
 [ 7 48 82]]
[[48  9  7]
 [71 53  7]
 [86 82 50]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


APPEND


In [66]:
b =  np.arange(1,10).reshape(3,3)
print(b)
np.append(b,np.ones((b.shape[0],1),dtype=int),axis=1)
# adding a new col to a 2d array
#b.shape[0] no of rows
#ADDING NEW ROW AND COLS
#MAKE A NEW COL
new_col = np.random.randint(1,100,(3,1))
#APPEND TO ARRAY AND STORE  MODIFIED ARRAY
new_col_array = np.append(b,new_col,axis=1)
new_row = np.random.randint(1,100,(1,4))
#APPENDED NEW ROW IN THE MODIFIED ARRAY
np.append(new_col_array,new_row,axis=0)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3, 49],
       [ 4,  5,  6, 38],
       [ 7,  8,  9, 31],
       [17, 55, 23, 46]])

CONCATINATE


In [74]:
a  =  np.arange(6).reshape(2,3)
b =  np.arange(6,12).reshape(2,3)
np.concatenate((a,b),axis=0)
np.concatenate((a,b),axis=1)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

UNIQUE


In [75]:
#give unique elements from  given numpy array in sorted order
array  = np.array([11,1,111,1,1,1,0,0,0,0,121,2,1,2,121,2,3])
np.unique(array)

array([  0,   1,   2,   3,  11, 111, 121])