In [1]:
import numpy as np

In [3]:
#z score minimization
# When we talk about normalizing a matrix (or a dataset in general,
# we're referring to the process of adjusting the values so that they meet certain conditions, often to make them more suitable for further analysis or
# #  to improve the performance of machine learning algorithms. Let's break this down in simple terms:0
# normalized value = value-mean_of_data/standard dev of the data
array = np.random.randint(1,1000,25).reshape(5,5)
normalization  = (array-np.mean(array))/np.std(array)
normalization

array([[ 1.11084878e+00, -1.06695506e+00, -4.08549246e-01,
        -2.43947794e-01,  1.40628728e+00],
       [-4.80298597e-01,  1.32187628e+00,  4.44001867e-01,
         2.58297664e-01, -1.67471427e+00],
       [ 4.48222417e-01, -6.02694549e-01,  8.44110013e-04,
        -1.35817301e+00, -4.54975297e-01],
       [ 2.32974364e-01, -6.61782250e-01,  5.14907108e-02,
         1.08974603e+00,  3.68031966e-01],
       [-1.45946621e+00, -1.84775682e+00,  1.44849278e+00,
         2.83620964e-01,  1.79457789e+00]])

In [12]:
array = np.arange(1,30)
mask  = (3<array)&(array<8)
array[mask]

array([4, 5, 6, 7])

In [14]:
print(sum(range(5),-1)) # sum will start from -1,0,1,2,3,4
from numpy import *
print(sum(range(5),-1)) # numpy dont conider one

9
10


In [15]:
array = np.random.randint(1,1000,25).reshape(5,5)
normalization  = (array-np.mean(array))/np.std(array)
np.round(normalization)

array([[ 1.,  1.,  0., -0., -1.],
       [ 1.,  1., -2.,  1., -1.],
       [ 1.,  0.,  0., -2.,  0.],
       [ 1., -0.,  1.,  1., -1.],
       [-0.,  1., -1., -1., -1.]])

In [23]:
def formula(a,b):
  x = a+b
  y = -a/2
  return x*y
array1= np.random.randint(1,100,9).reshape(3,3)
array2 = np.random.randint(70,120,9).reshape(3,3)
print(formula(array1,array2))


[[-5508.  -6960.  -5076.5]
 [-6351.  -4316.   -343. ]
 [-8772.   -605.  -5248. ]]


In [59]:
#convrting to polar_Cordinates
cord = np.random.randint(1,100,20).reshape(10,2)
print("IN CARTSIAN SYSTEM :  ")
print(cord)
print(" ")
rad = cord[:,0]
theta = cord[:,1]
r =  np.sqrt(rad**2 + theta**2)
angle = np.arctan(rad/theta)
cord.dtype= float
cord[:,0]=r
cord[:,1] = angle
print("IN POLAR SYSTEM : ")
print(cord)



IN CARTSIAN SYSTEM :  
[[70 61]
 [11 45]
 [90 80]
 [62 90]
 [72 75]
 [97 50]
 [54 42]
 [70 89]
 [30 10]
 [24 65]]
 
IN POLAR SYSTEM : 
[[ 92.84934033   0.85399267]
 [ 46.32493929   0.23974311]
 [120.41594579   0.84415399]
 [109.28860874   0.60322985]
 [103.96634071   0.76499283]
 [109.12836478   1.09485426]
 [ 68.41052551   0.90975316]
 [113.22985472   0.66646527]
 [ 31.6227766    1.24904577]
 [ 69.28924881   0.35370315]]


In [25]:
array =  np.full(10,1)
array.flags.writeable(write=False)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
x = np.random.randint(1,100,20)
for i in np.nditer(x):
  print(i ,end  = " ")

14 60 39 84 81 15 95 69 56 21 59 39 99 41 6 87 62 10 71 76 

In [77]:
number = np.full(3,1.232,dtype=float16)
#in int 32
number =  number.astype(np.int32)
number

array([1, 1, 1], dtype=int32)