In [1]:
import numpy as np

In [39]:
def febonachi(n):
  alpha = (1+np.sqrt(5))/2
  beta = (1-np.sqrt(5))/2
  return int( (alpha**n - beta**n)*(1/np.sqrt(5)))
array = np.arange(1,11)
length = len(array)
numbers= []
for i in range(length):
  numbers.append(febonachi(i))
print(numbers)



[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [55]:
array = np.array([1,2,3,0,0,0,1,0,0,0,0])
counts = np.where(array==0)
len(counts[0])

7

In [72]:
array  =  np.arange(1,10).reshape(3,3)
array.astype(np.int8)
array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
array =  np.zeros(3)
array[2] = 99
#making the numpy array only readable
array.setflags(write=False)
array[0] = 1000
array

array([1000.,    0.,   99.])

In [81]:
array =  np.array([0,0,0,1,1,1,2,3,4,0,0,0,0])
#with built in
np.trim_zeros(array) #BUILT IN METHOD
#second way
indices  = np.where(array!=0)
array[indices]
#third
MASK  = array!=0
array[MASK]

array([1, 1, 1, 2, 3, 4])

In [87]:
a =  np.random.randint(1,100,9).reshape(3,3)
print(a)
Sum = np.sum(np.diagonal(a))
Sum

[[30  3 86]
 [79 46 71]
 [71 75 77]]


153

In [95]:
#adding new row in numpy
#1)GIVEN
array =  np.random.randint(1,100,9).reshape(3,3)
print("ORIGNAL ARRAY")
print(array)
new_row = np.array([200,300,400])
array[0] = new_row
print("MODIFIED ARRAY")
print(array)
#MATCHES
a =  np.random.randint(1,100,9).reshape(3,3)
new_col = np.array([1000,4000,6000]).reshape(3,1)
# np.where(a[0])


ORIGNAL ARRAY
[[29 56 28]
 [90 56 59]
 [73 55 49]]
MODIFIED ARRAY
[[200 300 400]
 [ 90  56  59]
 [ 73  55  49]]


array([[1000],
       [4000],
       [6000]])